### ISSUE TITLE
Does not accept floats

### ISSUE THREAD

**Issue by hdzierz** [abbasovalex/django-SplitJSONWidget-form#13]
Hi There,

Jsonsplit does not accept floats. Shoud just suffice to add float in the test against unicode and int in _to_build. Will do a pull request in this.

Cheers

Helge

**Comment by abbasovalex** [comment]
@hdzierz it was added https://github.com/abbasovalex/django-SplitJSONWidget-form/commit/84d816ea716115d8da2a1978c9326586bb3161b6
