### ISSUE TITLE
Errors on django 1.6.11 or in similar versions

### ISSUE THREAD

**Issue by prakash-codesource** [abbasovalex/django-SplitJSONWidget-form#15]
```
if float(get_version()) < 1.9:
    from django.forms.util import flatatt
else:
    from django.forms.utils import flatatt
```

ValueError: invalid literal for float(): 1.6.11

Thanks

**Comment by abbasovalex** [comment]
@prakash-codesource thank! It was adjusted https://github.com/abbasovalex/django-SplitJSONWidget-form/commit/22e56c32707f7d01b407a7536c1c2696041ec7a7
