### ISSUE TITLE
Using for Dictionary, but when saving data gets changed.

### ISSUE THREAD

**Issue by NiranjanSingh** [abbasovalex/django-SplitJSONWidget-form#18]
Thank you for this awesome library. 

Solved many issues, but having this problem:

original data: {1: {'end_minute': 0, 'start_hour': 10, 'end_hour': 19, 'start_minute': 0}, 2: {'end_minute': 30, 'start_hour': 8, 'end_hour': 17, 'start_minute': 30}}

After saving it using django-admin it's getting saved as below in DB.

[{u'end_minute': u'0', u'start_hour': u'10', u'end_hour': u'19', u'start_minute': u'0'}, {u'end_hour': u'17', u'start_hour': u'8', u'end_minute': u'30', u'start_minute': u'30'}]

**Comment by abbasovalex** [comment]
Hi @NiranjanSingh ! It is a fact.
Still numbers keys can't used. It is old error https://github.com/abbasovalex/django-SplitJSONWidget-form/issues/2

**Comment by NiranjanSingh** [comment]
Yes, I have fixed this by editing _to_parse() method. Thanks!
